/*
  Warnings:

  - The values [DISEASE,CANCER,GENETIC,METABOLIC,INFECTIOUS,DEVELOPMENTAL,DIAGNOSIS,TREATMENT,SCREENING,PREVENTION,EMERGENCY,SYMPTOM,SYNDROME,COMPLICATION,SIDE_EFFECT,MUTATION,VARIANT,POLYMORPHISM,DELETION,INSERTION,FUSION,AMPLIFICATION,DRUG,THERAPY,SURGERY,RADIATION,GENE_THERAPY,BRAIN,HEART,LUNG,LIVER,KIDNEY,BONE,MUSCLE,BLOOD] on the enum `CategoryType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "CategoryType_new" AS ENUM ('ONCOLOGICAL', 'CARDIOVASCULAR', 'NEUROLOGICAL', 'RESPIRATORY', 'GASTROINTESTINAL', 'ENDOCRINE', 'IMMUNOLOGICAL', 'MUSCULOSKELETAL', 'DERMATOLOGICAL', 'GENETIC_DISORDER', 'INFECTIOUS_DISEASE', 'RARE_DISEASE', 'PRIMARY_DIAGNOSIS', 'SECONDARY_DIAGNOSIS', 'ACUTE_CARE', 'CHRONIC_CARE', 'PALLIATIVE_CARE', 'PREVENTIVE_CARE', 'CLINICAL_TRIAL', 'CHEMOTHERAPY', 'IMMUNOTHERAPY', 'TARGETED_THERAPY', 'HORMONE_THERAPY', 'RADIATION_THERAPY', 'SURGICAL', 'COMBINATION_THERAPY', 'EXPERIMENTAL_THERAPY', 'PEDIATRIC', 'ADULT', 'GERIATRIC', 'MATERNAL', 'FAMILIAL', 'CENTRAL_NERVOUS', 'PERIPHERAL_NERVOUS', 'CARDIAC', 'VASCULAR', 'RESPIRATION', 'DIGESTIVE', 'HEPATIC', 'PANCREATIC', 'RENAL', 'URINARY', 'REPRODUCTIVE', 'SKELETAL', 'MUSCULAR', 'INTEGUMENTARY', 'LYMPHATIC', 'ENDOCRINE_THYROID', 'ENDOCRINE_ADRENAL', 'ENDOCRINE_PITUITARY', 'OCULAR', 'AUDITORY', 'ORAL', 'JOINT', 'HEMATOLOGIC', 'IMMUNE');
ALTER TABLE "Patient" ALTER COLUMN "categories" TYPE "CategoryType_new"[] USING ("categories"::text::"CategoryType_new"[]);
ALTER TABLE "GenomicData" ALTER COLUMN "categories" TYPE "CategoryType_new"[] USING ("categories"::text::"CategoryType_new"[]);
ALTER TABLE "PhenotypeData" ALTER COLUMN "categories" TYPE "CategoryType_new"[] USING ("categories"::text::"CategoryType_new"[]);
ALTER TABLE "ImagingData" ALTER COLUMN "categories" TYPE "CategoryType_new"[] USING ("categories"::text::"CategoryType_new"[]);
ALTER TABLE "SignalData" ALTER COLUMN "categories" TYPE "CategoryType_new"[] USING ("categories"::text::"CategoryType_new"[]);
ALTER TYPE "CategoryType" RENAME TO "CategoryType_old";
ALTER TYPE "CategoryType_new" RENAME TO "CategoryType";
DROP TYPE "CategoryType_old";
COMMIT;
